kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: result-s2i
  labels:
    app: diary-app
spec:
  strategy:
    sourceStrategy:
      from:
        kind: DockerImage
        name: centos/nodejs-10-centos7
    type: Source
  source:
    type: Git
    git:
      uri: "https://github.com/takwa1925/openshift-diary-app.git"
      ref: main
    contextDir: diary-app/result/src
  output:
    to:
      kind: ImageStreamTag
      name: result:latest
